#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
CND_BUILDDIR=build
CND_DISTDIR=dist
# Debug configuration
CND_PLATFORM_Debug=MinGW-Windows
CND_ARTIFACT_DIR_Debug=dist/Debug/MinGW-Windows
CND_ARTIFACT_NAME_Debug=multiagent
CND_ARTIFACT_PATH_Debug=dist/Debug/MinGW-Windows/multiagent
CND_PACKAGE_DIR_Debug=dist/Debug/MinGW-Windows/package
CND_PACKAGE_NAME_Debug=multiagent.tar
CND_PACKAGE_PATH_Debug=dist/Debug/MinGW-Windows/package/multiagent.tar
# Release configuration
CND_PLATFORM_Release=MinGW-Windows
CND_ARTIFACT_DIR_Release=dist/Release/MinGW-Windows
CND_ARTIFACT_NAME_Release=multiagent
CND_ARTIFACT_PATH_Release=dist/Release/MinGW-Windows/multiagent
CND_PACKAGE_DIR_Release=dist/Release/MinGW-Windows/package
CND_PACKAGE_NAME_Release=multiagent.tar
CND_PACKAGE_PATH_Release=dist/Release/MinGW-Windows/package/multiagent.tar
# DebugParallel configuration
CND_PLATFORM_DebugParallel=MinGW-Windows
CND_ARTIFACT_DIR_DebugParallel=dist/DebugParallel/MinGW-Windows
CND_ARTIFACT_NAME_DebugParallel=multiagent
CND_ARTIFACT_PATH_DebugParallel=dist/DebugParallel/MinGW-Windows/multiagent
CND_PACKAGE_DIR_DebugParallel=dist/DebugParallel/MinGW-Windows/package
CND_PACKAGE_NAME_DebugParallel=multiagent.tar
CND_PACKAGE_PATH_DebugParallel=dist/DebugParallel/MinGW-Windows/package/multiagent.tar
# ReleaseParallel configuration
CND_PLATFORM_ReleaseParallel=MinGW-Windows
CND_ARTIFACT_DIR_ReleaseParallel=dist/ReleaseParallel/MinGW-Windows
CND_ARTIFACT_NAME_ReleaseParallel=multiagent
CND_ARTIFACT_PATH_ReleaseParallel=dist/ReleaseParallel/MinGW-Windows/multiagent
CND_PACKAGE_DIR_ReleaseParallel=dist/ReleaseParallel/MinGW-Windows/package
CND_PACKAGE_NAME_ReleaseParallel=multiagent.tar
CND_PACKAGE_PATH_ReleaseParallel=dist/ReleaseParallel/MinGW-Windows/package/multiagent.tar
